### ISSUE TITLE
Notifikationsmodul für niedrige Doi Balance

### ISSUE THREAD

**Issue by stallingerl** [webanizer/Consolino2IPFS#11]
@stallingerl 
Chron Job der eine Benachrichtigungsmail schickt, wenn die Doi balance unter einen bestimmten Wert fällt.

E-mail Einstellungen in Settings.js schreiben

**Comment by NiKrause** [comment]
Welche Cron Library haben wir hier?

**Comment by stallingerl** [comment]
Neuer RPC Call getbalance wurde eingefügt, mit dem geprüft wird ob noch genug Dois im Wallet sind und falls nicht, wird eine Benachrichtigungs E-mail verschickt. 

Die E-mail Einstellungen müssen in /src/sendNotification unter transporter angepasst werden. 

Falls der Kontostand unter 0.01 Doi liegt wird ein Error geworfen und der proof-of-existence unterbrochen. @inspiraluna  Kann man das so machen?
