### ISSUE TITLE
Fertiges script zum testen 3 Testfälle

### ISSUE THREAD

**Issue by stallingerl** [webanizer/Consolino2IPFS#12]
@davidreband @stallingerl 
1. Script soll mit einfachem Startbefehl zunächst mit docker-compose eine Doichain node im Regtest modus starten. 
             Passwort, host etc aus der Settings-demo lesen, die umbenannt wird zu Settings-test.js
2. Anschließend von einer Testdatei das Einlesen von Zählerdaten mit der Smartmeterobis testen
3. Weil der hash der test datei schon bekannt ist, kann mit assert das verhasen getestet werden
4. Anschließend wird der IPFS test gestartet. 
   4.1  Test Start von IPFS Node
   4.2  Test Abrufen der hochgeladenen Testdatei und sicherstellen, dass sie dem eingelesenen test file entspricht
5. Hash und CID an den Doichaintest übergeben. 
  5.1 Name_doi Befehl muss Status 200 haben
  5.2 Name_show RPC call und sicherstellen, dass der Hash in der doichain zu finden ist.

**Comment by davidreband** [comment]
1.
Test: npm run start:test
mocha test: npm test

2. erledigt
3. erledigt
4. 1. erledigt

**Comment by stallingerl** [comment]
@davidreband  es fehlt noch 12.3 und 12.4.2. 

Alle anderen Änderungen habe ich schon in dev gemerged und gepushed. 

Bräuchten für die letzten Änderungen einen neuen Branch.

**Comment by stallingerl** [comment]
Überarbeitet:
- nur noch eine Test suite für alle Testfälle
- neuer Test für das Verhashen der sml Testdateien
- neuer Test für IPFS: Gegenprüfen des hochgeladenen testHash mit ipfs.cat
