### ISSUE TITLE
Systemd Script für node.js index.js schreiben

### ISSUE THREAD

**Issue by NiKrause** [webanizer/Consolino2IPFS#6]
bisher muss Consoline2IPFS immer mit ```node index.js```gestartet werden. Das sollte automatisch beim Systemstart passieren.

**Comment by mrheat** [comment]
erledigt

**Comment by NiKrause** [comment]
kannst Du noch einen Commit machen? Wenn Du einen Commit machst, kannst Du ihn auch ein Hash-Zeichen mit der Issue Nummer eingeben, dann ist es gleich referenziert: Siehe: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#commit-shas

**Comment by NiKrause** [comment]
können wir das noch in das Readme aufnehmen? Hast Du es im Github?

**Comment by stallingerl** [comment]
@mrheat : 
liegt in /etc/systemd und wird dort über symlinks dann entsprechend aktiviert
