### ISSUE TITLE
Unit Tests bzw. Software tests schreiben.

### ISSUE THREAD

**Issue by NiKrause** [webanizer/Consolino2IPFS#9]
1. Zunächst einmal müssen wir die main.js testen, ohne, dass wir mit einem serial port physisch verbunden sind. (Kann man den seriellen Port emulierten oder gibt es andere Möglichkeiten diese Library zu testen? Hinweis: Bitte beim Hersteller der Library nachforschen, ob bereits Tests vorhanden sind. -Sollte es so sein, darauf kann man aufbauen.

2. Können wir die Daten ins IPFS schreiben und anstatt ins Doichain-Mainet ins Doichain Regtest schreiben. Prüfen ob sie darin in der Blockchain stehen.

3. Chai und Mocca benutzen
- https://mochajs.org/
- https://www.digitalocean.com/community/tutorials/how-to-test-a-node-js-module-with-mocha-and-assert-de

**Comment by mrheat** [comment]
1. Testing is an important feature of any library. To aid in our own tests we've developed a MockBinding a fake hardware binding that doesn't actually need any hardware to run. This class passes all of the same tests as our hardware based bindings and provides a few additional test related interfaces.

const SerialPort = require('@serialport/stream')
const MockBinding = require('@serialport/binding-mock')

SerialPort.Binding = MockBinding

// Create a port and enable the echo and recording.
MockBinding.createPort('/dev/ROBOT', { echo: true, record: true })
const port = new SerialPort('/dev/ROBOT')
The code can be found in the @serialport/binding-mock package.

siehe https://serialport.io/docs/guide-testing

**Comment by davidreband** [comment]
Test für SmartmeterObis ist ohne angeschlossenes Gerät erstellt

**Comment by davidreband** [comment]
IPFS-Test erstellt ein Test-Repository und löscht es nach dem Test

**Comment by davidreband** [comment]
Mocca wird für den test verwendet
